---
driver:
  name: dokken

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  # @see https://github.com/someara/dokken-images
  # @see https://hub.docker.com/r/dokken/
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
  - name: centos-7
    driver:
      image: dokken/centos-7

suites:
  - name: default
    run_list:
      - recipe[test-certbot-exec::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      certbot_exec:
        print_cmd: true
        server: stage
